### ISSUE TITLE
Application is not starting sometimes, but still in process after that

### ISSUE THREAD

**Issue by i4004** [i4004/SailPlayer#134]

**Comment by i4004** [comment]
Because previous process is already running

**Comment by i4004** [comment]
Related to #130

**Comment by dpurgin** [comment]
мб ошибка в QML, из-за которой QQuickView не создаёт окно?

**Comment by i4004** [comment]
Нет, там процесс предыдущего SailPlayer остаётся в системе из-за того и музыка продолжает играть, если приложение было закрыто во время проигрывания, но это происходит только если плеер, например, пол часа на паузе стоят. Как будто что-то происходить с блокировкой аудиоресурса.

**Comment by i4004** [comment]
Playing state on cover page is not reflect state change after that.

**Comment by i4004** [comment]
При отключении наушников статус также сбивается.
