### ISSUE TITLE
Not playing at all after fresh install on new system

### ISSUE THREAD

**Issue by i4004** [i4004/SailPlayer#137]

**Comment by i4004** [comment]
gstreamer-1.0-plugins-good should be installed

**Comment by dpurgin** [comment]
добавь в Requires: в yaml или spec

**Comment by i4004** [comment]
Добавлял, видимо название было не корректное либо не везде куда надо добавил, при установке на устройство была ошибка, что "nothing provides gstreamer-1.0-plugins-good", буду разбираться.

**Comment by dpurgin** [comment]
Там название такое: gstreamer1.0-plugins-good (без дефиса после gstreamer)
