### ISSUE TITLE
Запоминать позицию в последнем воспроизводимом файле

### ISSUE THREAD

**Issue by dpurgin** [i4004/SailPlayer#52]
Надо запоминать позицию в последнем воспроизводимом файле, и можно было бы запускать воспроизведение с этого же места (полезно для аудиокниг)

**Comment by i4004** [comment]
Запускать автоматически при открытии плеера с прошлого места или просто запоминать позицию и устанавливать её при открытии плеера?

**Comment by dpurgin** [comment]
Думаю, надо просто устанавливать при открытии на паузе.
