### ISSUE TITLE
Long album names overlap with other items

### ISSUE THREAD

**Issue by dpurgin** [i4004/SailPlayer#89]
See attached screenshot
![20150221164228](https://cloud.githubusercontent.com/assets/8401313/6313828/5161ae88-b9e9-11e4-84bc-0de827689b69.jpg)

**Comment by i4004** [comment]
Ok with correct encoding

**Comment by dpurgin** [comment]
still doesn't work sometimes. See attached screenshots

![20150222232653](https://cloud.githubusercontent.com/assets/8401313/6319571/9e4d0f60-baea-11e4-8630-5ea1c504447f.jpg)
![20150222232710](https://cloud.githubusercontent.com/assets/8401313/6319572/9e4dc324-baea-11e4-8b08-2d52b57bc9b6.jpg)

**Comment by i4004** [comment]
Там оказывается, именно при добавлении файлов почему-то съезжает :) Issues #90

**Comment by i4004** [comment]
Possibly it is a bug in SilicaListView or ListView because of wrong calculation of item with wrapped text on display.
